# Generated by Django 5.0.1 on 2025-01-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('assets', '0002_initial_categories'),
    ]

    operations = [
    ]
