# Generated by Django 5.0.1 on 2025-01-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_merge_0002_initial_0002_initial_categories'),
        ('assets', '0004_initial_asset_types'),
    ]

    operations = [
    ]
