# Generated by Django 5.0.1 on 2025-01-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_merge_20250106_1053'),
        ('assets', '0005_remove_brand_field'),
    ]

    operations = [
    ]
