# Generated by Django 5.0.1 on 2025-01-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_merge_20250106_1137'),
        ('assets', '0006_optional_sku'),
    ]

    operations = [
    ]
