# Generated by Django 5.0.1 on 2025-01-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_merge_0006_merge_20250106_1137_0006_optional_sku'),
        ('assets', '0008_update_models'),
    ]

    operations = [
    ]
