# Generated by Django 5.0.1 on 2025-01-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_merge_20250106_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tag_number',
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assettype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='placement',
            table=None,
        ),
    ]
